### ISSUE TITLE
Memory leak _with_ weak refs

### ISSUE THREAD

**Issue by davedoesdev** [substack/dnode#150]
I have a long running test which creates lots of child processes and uses `dnode` to communicate with them (thanks for `dnode`!).

The strange thing is I'm seeing much more memory usage with the default behaviour of  `dnode` compared to when I pass `{weak: false}` (after 30 mins of the test running, 1.9Gb vs 0.3Gb).

I used `webkit-devtools-agent` to try to figure it out. All I could work out was that some global reference was being held to the callbacks. This should be the other way round, right - they should disappear with weak refs in play?

I haven't had chance yet to investigate further but was wondering if you had any ideas?

Thanks

**Comment by robcolburn** [comment]
@davedoesdev - still an issue? Have you tried posting the issue to `weak`?

**Comment by davedoesdev** [comment]
@robcolburn this is now fixed! Tested with dnode 1.2.2.
