### ISSUE TITLE
Support of node 0.12

### ISSUE THREAD

**Issue by apsavin** [substack/dnode#161]
It seems that something is wrong with dependencies of dnode:

```
uncaught exception: Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (/Users/apsavin/Projects/bnsf/node_modules/phantom/node_modules/dnode/node_modules/weak/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/Users/apsavin/Projects/bnsf/node_modules/phantom/node_modules/dnode/node_modules/weak/lib/weak.js:7:35)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```
To be exact, with `weak` module. Update to 0.4.0 version of weak fixes the problem.

**Comment by apsavin** [comment]
Anybody?..

**Comment by seethroughtrees** [comment]
+1 weak 0.3.x has iojs 2.0 issues as well.

**Comment by seethroughtrees** [comment]
So, it looks like the issue is the actual dependency of weak.  https://github.com/TooTallNate/node-weak/issues/45

Will see what I can do to get a PR over there first...

**Comment by seethroughtrees** [comment]
So, to confirm the issue, node-weak depends on nan, which needs to be updated.  The node-weak repo on Github is fixed, but waiting for a push to npm.  

https://github.com/TooTallNate/node-weak/issues/45

I have tested by installing node-weak from github instead.  And running ```npm test``` on dnode, all installs and passes as expected.  Hopefully we can get that pushed, so we can update dnode, and all that depends on it.

Thanks.

**Comment by substack** [comment]
I've added you both as collaborators on github and npm if you want to fix this. I haven't used dnode in a while so it's probably time to hand this repo off.

**Comment by seethroughtrees** [comment]
Happy to help.  When I hear back from the node-weak issue, I'll update accordingly.

**Comment by fujifish** [comment]
Any thoughts on when this new version might get released to NPM?

**Comment by seethroughtrees** [comment]
@fujifish gonna work on this tonight.  keep you updated...

**Comment by apsavin** [comment]
@seethroughtrees @substack It seems that I have no rights to release (to `npm publish`) a new version of dnode. Can you please do it or give me such rights?

**Comment by seethroughtrees** [comment]
No problem @apsavin I just publish the update.  Whats your npm username?

**Comment by apsavin** [comment]
Thanks, @seethroughtrees. My npm username is asavin, email box.for.postman at gmail.com.

**Comment by seethroughtrees** [comment]
Just sent you npm access @apsavin let me know if you have any issues.

**Comment by apsavin** [comment]
No issues, thanks, @seethroughtrees!
